# Generated by Django 5.2.3 on 2025-07-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendersync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
