# Generated by Django 5.2.1 on 2025-06-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
