# Generated by Django 5.2.1 on 2025-06-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='room_id',
            new_name='meeting_id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='allow_participant_share_screen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='allow_participant_unmute',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_waiting_room_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participants',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting Room'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-Host'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_video_on', models.BooleanField(default=True)),
                ('is_hand_raised', models.BooleanField(default=False)),
                ('is_sharing_screen', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
