# Generated by Django 5.2.1 on 2025-06-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('instant', 'Instant Meeting'), ('scheduled', 'Scheduled Meeting')], default='instant', max_length=20),
        ),
    ]
