# Generated by Django 5.2.1 on 2025-06-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
