# Generated by Django 5.2.3 on 2025-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_participant_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
