# Generated by Django 5.2.3 on 2025-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_recording',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
