# Generated by Django 5.2.3 on 2025-07-31 11:06

import django.db.models.deletion
import jobboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('keybook', 'Key Book'), ('notes', 'Notes'), ('pastpapers', 'Past Papers')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('home', 'Home')], max_length=20)),
                ('class_level', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, max_length=150, null=True)),
                ('preffered_method', models.CharField(blank=True, max_length=100, null=True)),
                ('days_to_study', models.CharField(blank=True, max_length=100, null=True)),
                ('timing_to_study', models.CharField(blank=True, max_length=100, null=True)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('cnic_or_form_b_pic', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('degree', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('attendance', models.JSONField(default=dict)),
                ('purchased_online_resources', models.ManyToManyField(blank=True, to='jobboard.onlineresource')),
                ('qualifications', models.ManyToManyField(blank=True, to='jobboard.qualification')),
                ('scheduled_classes', models.ManyToManyField(blank=True, to='jobboard.scheduledclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, to='jobboard.subject')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.studentprofile'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.subject'),
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_type', models.CharField(choices=[('online', 'Online Tuition'), ('regular', 'Regular Job'), ('home', 'Home Tuition')], default='online', max_length=10)),
                ('classes', models.CharField(help_text="Comma-separated class levels (e.g. '9th,10th')", max_length=200, null=True)),
                ('days_to_study', models.CharField(default='Mon to Fri', help_text='e.g. Mon,Wed,Fri', max_length=100)),
                ('time_to_study', models.CharField(help_text='e.g. 4pm-6pm', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('qualification_required', models.CharField(default='Bachelors', max_length=200)),
                ('experience_required', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, help_text='Contact number or email', max_length=100, null=True)),
                ('study_mode', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.employerprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.studentprofile')),
                ('subjects', models.ManyToManyField(to='jobboard.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TutorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='FREE', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='payments',
            field=models.ManyToManyField(blank=True, to='jobboard.tutorpayment'),
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('cnic', models.CharField(default='XXXXX-XXXXXXX-X', max_length=15)),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to=jobboard.models.upload_to_cnic_front)),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to=jobboard.models.upload_to_cnic_back)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=jobboard.models.upload_to_profile)),
                ('degree_image', models.ImageField(blank=True, null=True, upload_to=jobboard.models.upload_to_degree)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number_1', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_package', models.CharField(blank=True, max_length=100, null=True)),
                ('timings_required', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('areas_to_teach', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('can_teach_online', models.BooleanField(default=False)),
                ('minimum_qualification_required', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_required', models.CharField(blank=True, max_length=255, null=True)),
                ('qualifications', models.ManyToManyField(blank=True, to='jobboard.qualification')),
                ('saved_jobs', models.ManyToManyField(blank=True, related_name='saved_by', to='jobboard.jobpost')),
                ('subjects', models.ManyToManyField(blank=True, to='jobboard.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.tutorprofile'),
        ),
        migrations.AddField(
            model_name='onlineresource',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.tutorprofile'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.jobpost')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.tutorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='purchased_video_courses',
            field=models.ManyToManyField(blank=True, to='jobboard.videocourse'),
        ),
    ]
